version: '3'
services:
  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-pro:7.71.16
    container_name: artifactory
    restart: always
    healthcheck:
      test: curl -sf http://localhost:8082/artifactory/api/system/ping || exit 1
      timeout: 3s
      start_period: 30s
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    network_mode: "host"
  vault:
    image: hashicorp/vault:1.14.8
    container_name: vault
    command: ["server", "-log-level=debug", "-dev", "-dev-plugin-dir=/vault/plugins"]
    restart: always
    healthcheck:
      test: wget -O- http://localhost:8200/v1/sys/health
      interval: 10s
      timeout: 3s
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DISABLE_MLOCK: "true"
    volumes:
      - /vault/plugins
    network_mode: "host"
